export default [
  {
    files: ["**/*.ts"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        global: "readonly",
        module: "readonly",
        require: "readonly",
        exports: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        Promise: "readonly",
        Map: "readonly",
        Set: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        Date: "readonly",
        Math: "readonly",
        JSON: "readonly",
        Object: "readonly",
        Array: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        Symbol: "readonly",
        Error: "readonly",
        TypeError: "readonly",
        ReferenceError: "readonly",
        RangeError: "readonly",
        SyntaxError: "readonly",
        EvalError: "readonly",
        URIError: "readonly",
        RegExp: "readonly",
        Intl: "readonly",
        DataView: "readonly",
        ArrayBuffer: "readonly",
        SharedArrayBuffer: "readonly",
        Float32Array: "readonly",
        Float64Array: "readonly",
        Int8Array: "readonly",
        Int16Array: "readonly",
        Int32Array: "readonly",
        Uint8Array: "readonly",
        Uint16Array: "readonly",
        Uint32Array: "readonly",
        Uint8ClampedArray: "readonly",
        BigInt: "readonly",
        BigInt64Array: "readonly",
        BigUint64Array: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        crypto: "readonly",
        performance: "readonly",
        fetch: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        ReadableStream: "readonly",
        WritableStream: "readonly",
        TransformStream: "readonly",
        Response: "readonly",
        Request: "readonly",
        Headers: "readonly",
        FormData: "readonly",
        File: "readonly",
        Blob: "readonly",
        EventTarget: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        NodeJS: "readonly"
      }
    },
    rules: {
      "no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
      "no-console": "off",
      "prefer-const": "error",
      "no-var": "error",
      "eqeqeq": ["error", "always"],
      "curly": ["error", "all"],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-script-url": "error",
      "no-self-compare": "error",
      "no-throw-literal": "error",
      "no-unreachable": "error",
      "no-unused-expressions": "error",
      "no-useless-catch": "error",
      "no-useless-return": "error",
      "require-await": "error",
      "no-return-await": "error",
      "no-async-promise-executor": "error",
      "no-await-in-loop": "warn",
      "no-promise-executor-return": "error",
      "no-return-assign": "error",
      "no-self-assign": "error",
      "no-unmodified-loop-condition": "error",
      "no-unreachable-loop": "error",
      "no-constant-condition": "warn",
      "no-duplicate-imports": "error",
      "no-useless-backreference": "error",
      "no-useless-computed-key": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "prefer-template": "error",
      "template-curly-spacing": "error",
      "arrow-spacing": "error",
      "generator-star-spacing": "error",
      "yield-star-spacing": "error",
      "rest-spread-spacing": "error",
      "comma-dangle": ["error", "always-multiline"],
      "semi": ["error", "always"],
      "quotes": ["error", "single", { "avoidEscape": true }],
      "no-trailing-spaces": "error",
      "eol-last": "error",
      "indent": ["error", 2, { "SwitchCase": 1 }],
      "linebreak-style": ["error", "unix"],
      "max-len": ["error", { "code": 120, "tabWidth": 2 }],
      "object-curly-spacing": ["error", "always"],
      "array-bracket-spacing": ["error", "never"],
      "space-before-function-paren": ["error", { "anonymous": "always", "named": "never", "asyncArrow": "always" }],
      "keyword-spacing": "error",
      "space-infix-ops": "error",
      "spaced-comment": ["error", "always", { "markers": ["/"] }],
      "switch-colon-spacing": "error",
      "no-empty": ["error", { "allowEmptyCatch": true }]
    }
  }
]