import { spawn } from 'node:child_process';
const env = { ...process.env, MASTERCAM_MCP_BACKEND: 'mock', MASTERCAM_MCP_HTTP_TOKEN: 'smoke-token', MASTERCAM_MCP_HTTP_PORT: '8799', MASTERCAM_MCP_ALLOWED_ORIGINS: 'https://allowed.example' };
const child = spawn(process.execPath, ['node_modules/tsx/dist/cli.mjs', 'src/http.ts'], { env, stdio: ['ignore', 'pipe', 'pipe'] });
await new Promise(resolve => setTimeout(resolve, 2500));
const response = await fetch('http://127.0.0.1:8799/mcp', { method: 'POST', headers: { authorization: 'Bearer smoke-token', 'content-type': 'application/json', accept: 'application/json, text/event-stream' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 'http-smoke', version: '1' } } }) });
const body = await response.text();
const denied = await fetch('http://127.0.0.1:8799/mcp', { method: 'POST', headers: { authorization: 'Bearer smoke-token', origin: 'https://blocked.example', 'content-type': 'application/json' }, body: '{}' });
const allowed = await fetch('http://127.0.0.1:8799/mcp', { method: 'POST', headers: { authorization: 'Bearer smoke-token', origin: 'https://allowed.example', 'content-type': 'application/json', accept: 'application/json, text/event-stream' }, body: '{}' });
console.log(JSON.stringify({ status: response.status, deniedOrigin: denied.status, allowedOrigin: allowed.status, session: response.headers.get('mcp-session-id'), body: body.slice(0, 300) }, null, 2));
if (response.status !== 200 || denied.status !== 401 || allowed.status === 401) process.exitCode = 1;
child.kill();
