// @ts-nocheck
import { TIER_ORDER } from "./contracts.js";
import type { CapabilityTier } from "./contracts.js";

export interface CapabilityEntry {
  name: string;
  supported: boolean;
  riskClass: "read" | "mutation" | "advanced";
  requiresActiveDocument?: boolean;
  requiresRegeneration?: boolean;
  /** Which backend implements it: mock | legacy-adapter | 2027-adapter. */
  backend: string;
  tier: CapabilityTier;
  reason?: string;
  mappingVersion: number;
}

const read = (name: string, backend = "mock"): CapabilityEntry => ({
  name, supported: true, riskClass: "read", backend, tier: "IMPLEMENTED", mappingVersion: 1
});
const mutation = (name: string, backend = "mock", reason?: string): CapabilityEntry => ({
  name, supported: true, riskClass: "mutation", backend, tier: "IMPLEMENTED", requiresRegeneration: true, mappingVersion: 1, ...(reason ? { reason } : {})
});
const unavailable = (name: string, reason: string): CapabilityEntry => ({
  name, supported: false, riskClass: "mutation", backend: "none", tier: "UNAVAILABLE", reason, mappingVersion: 0
});

/** Renders docs/CAPABILITIES.md; the test suite asserts the checked-in doc matches. */
export function renderCapabilitiesDoc(): string {
  const rows = CAPABILITY_REGISTRY.map(entry => {
    const reason = entry.reason ?? "";
    return `| ${entry.name} | ${entry.supported ? "yes" : "no"} | ${entry.riskClass} | ${entry.backend} | ${entry.tier} | ${reason} |`;
  });
  const counts = {
    total: CAPABILITY_REGISTRY.length,
    supported: CAPABILITY_REGISTRY.filter(entry => entry.supported).length,
    liveVerified: CAPABILITY_REGISTRY.filter(entry => entry.tier.startsWith("LIVE_")).length
  };
  return `# Capability status

<!-- GENERATED by scripts/generate-capabilities.ts from src/capabilities.ts. Do not edit by hand; run \`pnpm run docs:capabilities\`. -->

The registry is the single source of truth for what this server advertises.
Tiers follow audit section 66: \`UNAVAILABLE\` < \`DISCOVERED\` < \`IMPLEMENTED\` < \`LIVE_READ_VERIFIED\` < \`LIVE_WRITE_VERIFIED\`.
A tier is raised only after the licensed acceptance harness passes against the matching Mastercam release.

Counts: ${counts.total} capabilities declared, ${counts.supported} supported, **${counts.liveVerified} live verified**.

| Tool | Supported | Risk | Backend | Tier | Notes |
| --- | --- | --- | --- | --- | --- |
${rows.join("\n")}

## Reading this table honestly

- \`IMPLEMENTED\` means the mapping exists and passes fixture tests. It is **not** evidence that it works against a real Mastercam release.
- The native add-in's capability registry (Stage A) currently reports only \`mastercam_status\` and \`mastercam_capabilities\` as live; every inspection or mutation tool returns \`UNSUPPORTED_CAPABILITY\` over the bridge until a release-specific adapter is live-verified.
- Simulation and collision results from the fixture backend are synthetic and never prove machine safety.
- Posting, cycle start, DNC, and script execution are deliberately unavailable.
`;
}

export const CAPABILITY_REGISTRY: CapabilityEntry[] = [
  // environment
  read("mastercam_status"), read("mastercam_capabilities"), read("mastercam_doctor"),
  read("mastercam_help"), read("list_tool_categories"), read("discover_capabilities"),
  read("get_compatibility_matrix"), read("get_version_report"), read("client_setup_check"),
  read("get_fixture_info"), read("get_audit_history"), read("mastercam_plan"),
  // inspection
  read("get_active_part"), read("get_geometry_summary"), read("get_selection"), read("get_selected_entities"),
  read("list_machine_groups"), read("get_machine_groups"), read("get_machine_context"),
  read("get_stock"), read("get_wcs"), read("get_post_processor"), read("get_programming_context"),
  read("list_operations"), read("get_operation"), read("get_operation_parameters"), read("find_operations"),
  read("explain_operation"), read("get_operation_risks"), read("get_dirty_toolpaths"), read("get_toolpath_status"),
  read("estimate_cycle_time"), read("compare_toolpaths"), read("list_tools"), read("get_tool"),
  read("capture_view"), read("inspect"), read("measure"), read("assert"),
  read("generate_setup_sheet"), read("compare_tool_databases"), read("compare_nc_files"), read("validate_machine_profile"),
  // controlled mutation workflow (fixture-verified; live tier requires acceptance runs)
  mutation("preview_operation_parameters"),
  mutation("apply_operation_parameter_preview"),
  mutation("rollback_change"),
  mutation("set_feed_speed", "mock", "legacy direct path; prefer preview/apply workflow"),
  mutation("change_tool"), mutation("regenerate_toolpath"), mutation("update_stock"),
  // advanced
  { name: "run_simulation", supported: true, riskClass: "advanced", backend: "mock", tier: "IMPLEMENTED", mappingVersion: 1, reason: "Fixture simulation is synthetic and never evidence of machine safety" },
  { name: "detect_collisions", supported: true, riskClass: "advanced", backend: "mock", tier: "IMPLEMENTED", mappingVersion: 1, reason: "Fixture collision results are synthetic" },
  // deliberately unavailable (audit sections 60/79)
  unavailable("post_program", "NC release is intentionally outside project scope for safety"),
  unavailable("cycle_start", "Machine execution is intentionally outside project scope for safety"),
  unavailable("send_dnc", "Direct machine communication is intentionally outside project scope for safety"),
  unavailable("execute_script", "Arbitrary execution is intentionally outside project scope for safety")
];

export function capability(name: string): CapabilityEntry | undefined {
  return CAPABILITY_REGISTRY.find(entry => entry.name === name);
}

export function capabilityReport(backendKind: "mock" | "live" = "mock") {
  const byTier = new Map<CapabilityTier, number>();
  for (const tier of TIER_ORDER) byTier.set(tier, 0);
  for (const entry of CAPABILITY_REGISTRY) byTier.set(entry.tier, (byTier.get(entry.tier) ?? 0) + 1);
  return {
    backend: backendKind,
    live: backendKind === "live",
    verificationTiers: TIER_ORDER,
    counts: Object.fromEntries(byTier),
    capabilities: CAPABILITY_REGISTRY,
    note: "IMPLEMENTED means fixture-verified only. LIVE_*_VERIFIED tiers require the licensed acceptance harness on a real Mastercam release."
  };
}
