import { TIER_ORDER } from "./contracts.js";
import type { CapabilityTier } from "./contracts.js";
import { TOOL_MANIFEST } from "./tool-manifest.js";

export interface CapabilityEntry {
  name: string;
  supported: boolean;
  riskClass: "read" | "mutation" | "advanced";
  requiresActiveDocument?: boolean;
  requiresRegeneration?: boolean;
  backend: string;
  tier: CapabilityTier;
  reason?: string;
  mappingVersion: number;
}

function riskClass(category: string): CapabilityEntry["riskClass"] {
  if (category === "write") return "mutation";
  if (category === "advanced" || category === "forbidden") return "advanced";
  return "read";
}

function backendLabel(entry: typeof TOOL_MANIFEST[number]): string {
  const backends = [
    entry.mockSupport ? "mock" : "",
    entry.legacySupport ? "legacy-adapter" : "",
    entry.mc2027Support ? "2027-adapter" : ""
  ].filter(Boolean);
  return backends.length ? backends.join("+") : "none";
}

export const CAPABILITY_REGISTRY: CapabilityEntry[] = TOOL_MANIFEST.map(entry => ({
  name: entry.name,
  supported: entry.registered && entry.mockSupport,
  riskClass: riskClass(entry.category),
  requiresActiveDocument: entry.requiresExactTarget || ["get_active_part", "get_stock", "get_wcs", "list_operations"].includes(entry.name),
  requiresRegeneration: entry.requiresRegeneration,
  backend: backendLabel(entry),
  tier: entry.tier,
  reason: entry.tierEvidence,
  mappingVersion: entry.registered ? 1 : 0
}));

export function renderCapabilitiesDoc(): string {
  const rows = CAPABILITY_REGISTRY.map(entry =>
    `| ${entry.name} | ${entry.supported ? "yes" : "no"} | ${entry.riskClass} | ${entry.backend} | ${entry.tier} | ${entry.reason ?? ""} |`
  );
  const counts = {
    total: CAPABILITY_REGISTRY.length,
    supported: CAPABILITY_REGISTRY.filter(entry => entry.supported).length,
    liveVerified: CAPABILITY_REGISTRY.filter(entry => entry.tier.startsWith("LIVE_")).length
  };
  return `# Capability status

<!-- GENERATED by scripts/generate-capabilities.ts from src/tool-manifest.ts. Do not edit by hand; run \`pnpm run docs:capabilities\`. -->

The tool manifest is the canonical source of truth for MCP registration, policy categories, support metadata, and this table.
Tiers: \`UNAVAILABLE\` < \`DISCOVERED\` < \`IMPLEMENTED\` < \`LIVE_READ_VERIFIED\` < \`LIVE_WRITE_VERIFIED\`.
A tier is raised only after a licensed live acceptance run against the matching Mastercam release.

Counts: ${counts.total} capabilities declared, ${counts.supported} fixture-supported, **${counts.liveVerified} live verified**.

| Tool | Fixture supported | Risk | Backends | Tier | Notes |
| --- | --- | --- | --- | --- | --- |
${rows.join("\n")}

## Reading this table honestly

- \`IMPLEMENTED\` means code exists and fixture/contract tests can exercise it. It is not proof that a real Mastercam release supports the tool.
- The native Stage A adapters currently advertise only \`mastercam_status\` and \`mastercam_capabilities\`; other live tools remain unavailable until release-specific mappings are implemented and accepted.
- Simulation and collision results from the fixture backend are synthetic and never prove machine safety.
- Posting, cycle start, DNC, and arbitrary script execution are deliberately unavailable.
`;
}

export function capability(name: string): CapabilityEntry | undefined {
  return CAPABILITY_REGISTRY.find(entry => entry.name === name);
}

export function capabilityReport(backendKind: "mock" | "live" = "mock") {
  const byTier = new Map<CapabilityTier, number>();
  for (const tier of TIER_ORDER) byTier.set(tier, 0);
  for (const entry of CAPABILITY_REGISTRY) {
    byTier.set(entry.tier, (byTier.get(entry.tier) ?? 0) + 1);
  }
  return {
    backend: backendKind,
    live: backendKind === "live",
    verificationTiers: TIER_ORDER,
    counts: Object.fromEntries(byTier),
    capabilities: CAPABILITY_REGISTRY,
    note: "IMPLEMENTED is not live verification. LIVE_* tiers require evidence from a licensed live acceptance run."
  };
}
